### ISSUE TITLE
Do we still need to build our own Dashboard?

### ISSUE THREAD

**Issue by epugh** [o19s/chorus-opensearch-edition#91]
Looking at the dashboard config in the ubi plugin, we may not need to build our own dashboard Dockerfile anymore:

```

  os-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - 5601
    environment:
      OPENSEARCH_HOSTS: '["http://os01:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - os01
    networks:
      - ubi-dev-os-net
```
